config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :cars do
    resources :bookings, only: %i[new create]
  end

  resources :bookings, only: [] do
    get 'confirmation', on: :member
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :car
end

app/models/car.rb
class Car < ApplicationRecord
  belongs_to :user

  has_many :bookings

  delegate :ends_at, to: :current_booking, prefix: true

  def unavailable?
    current_booking.present?
  end

  # with delegate, we don't need this method
  # def current_booking_ends_at
  #   return unless unavailable?

  #   current_booking.ends_at
  # end

  def current_booking
    bookings.where(starts_at: ..Date.today).where(ends_at: Date.today..).last
  end

  has_many_attached :photos, dependent: :destroy
  has_many :bookings, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  has_many :cars
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_car, except: :confirmation

  def new
    @booking = Booking.new
  end

  def confirmation
    @booking = Booking.find(params[:id])
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.car = @car
    @booking.user = current_user

    start_date = Date.parse(booking_params[:starts_at])
    end_date = Date.parse(booking_params[:ends_at])
    days = (end_date - start_date).to_i

    @booking.total_price = days * @car.price_per_day.to_i

    if @booking.save
      redirect_to confirmation_booking_path(@booking)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def set_car
    @car = Car.find(params[:car_id])
  end

  def booking_params
    params.require(:booking).permit(:starts_at, :ends_at)
  end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only: %i[show edit update destroy]

  def index
    @cars = Car.all
  end

  def show
    @car = Car.find(params[:id])
  end

  def new
    @car = Car.new
  end

  def create
    @car = Car.new(car_params)
    @car.user = current_user
    if @car.save
      redirect_to car_path(@car)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @car.update(car_params)
      redirect_to car_path(@car)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @car.destroy

    redirect_to cars_path, status: :see_other
  end

  private

  def set_car
    @car = Car.find(params[:id])
  end

  def car_params
    params.require(:car).permit(:brand, :model, :fuel_type, :category, :location, :year, :space_available, :price_per_day, :car_available, photos: [])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/confirmation.html.erb
<div class="confirmation-card">
  <div class="card-title1">
    <h1 class="text_shadows" style="color: white">
      Congratulations, your booking was successful! 🎉 <span class="card-subtitle"> Total price is: <%= @booking.total_price %> <i class="fa-solid fa-euro-sign"></i> </span>
    </h1>
  </div>
    <div class="card-video">
      <video id="my-video" class="video-js" controls preload="auto" width="100%" height="auto">
        <source src="https://res.cloudinary.com/dw8bkl8ak/video/upload/v1677839194/Y2Mate.is_-_Tokyo_Drift_Tractor_Meme-9Bma8yH3CVQ-720p-1655156207687_bujtpj.mp4" type="video/mp4">
      </video>
    </div>
</div>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Rampart+One&display=swap" rel="stylesheet">

app/views/bookings/new.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-12">
      <article class="blog-card">
        <div class="blog-card__background">
          <div class="card__background--wrapper">
            <div class="card__background--main" style="background-image: url('https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/LaFerrari_at_Goodwood_2014_006.jpg/460px-LaFerrari_at_Goodwood_2014_006.jpg');">
              <div class="card__background--layer"></div>
            </div>
          </div>
        </div>
        <div class="blog-card__head">
          <span class="date__box">
            <span class="date__day"><%= Date.today %></span>
            <span class="date__month"></span>
          </span>
        </div>
        <div class="blog-card__info">
          <h5>Would you like to book this car</h5>
          <p>
            <a href="#" class="icon-link mr-3"><i class="fa-solid fa-car"></i> <%= @car.brand %></a>
            <a href="#" class="icon-link"><i class="fa-solid fa-flag-checkered"></i> <%= @car.model %></a>
          </p>
          <%= simple_form_for [@car, @booking] do |f|%>
          <div class="form-book" data-controller="total-price" data-total-price-daily-price-value="<%= @car.price_per_day %>">
            <%= f.input :starts_at, as: :date, html5: true, input_html: { data: { total_price_target: "startsAt", action: "change->total-price#calculateTotalPrice" } }, class: "form-control" %>
            <%= f.input :ends_at, as: :date, html5: true, input_html: { data: { total_price_target: "endsAt", action: "change->total-price#calculateTotalPrice" } }, class: "form-control" %>
            <div class="text-content">
              <h4>Book amount:</h4>
              <h5 data-total-price-target="finalPrice"></h5><h5>€</h5>
            </div>
          </div>
           <%= f.submit "Book Now", class:"btn btn--with-icon"%>
          <% end %>
        </div>
      </article>
    </div>
  </div>
</div>
<section class="detail-page">
  <div class="container mt-5">

  </div>
</section>

app/views/cars/edit.html.erb
<script src="https://cdnjs.cloudflare.com/ajax/libs/cloudinary/2.24.1/cloudinary.min.js"></script>

<div class="container mt-5">
  <div class="newsletter-subscribe">
    <div class="container">
      <div class="intro">
        <h2 class="text-center">Edit you car!</h2>
        <p class="text-center">Update your car and it's details!</p>
      </div>
    <div class="container p-2 mt-5">
      <%= simple_form_for (@car), html: { class: "form"} do |f| %>
      <div class="row">
        <div class="col-md-4 select">
          <div class="form-group">
            <%= f.input :brand, class: "form-control" %>
          </div>
        </div>
        <div class="col-md-4 select">
          <div class="form-group">
            <%= f.input :model, class: "form-control bg-primary" %>
          </div>
        </div>
        <div class="col-md-4 select">
          <div class="form-group">
            <%= f.input :price_per_day, class: "form-control" %>
          </div>
        </div>
        <div class="col-md-4 select">
          <div class="form-group">
            <%= f.input :location, class: "form-control" %>
          </div>
        </div>
        <div class="col-md-4 select">
          <div class="form-group">
            <%= f.input :year, class: "form-control" %>
          </div>
        </div>
        <div class="col-md-4 select">
          <div class="form-group mt-5">
            <%= f.label :fuel_type %>
            <%= f.select :fuel_type, [["Gasoline", "Gasolin"], ["Diesel", "Diesel"], ["GPL", "GPL"], ["Electric", "Electric"]], class:"form-select", aria_label:"Default select example" %>
          </div>
        </div>
        <div class="col-md-4 select">
          <div class="form-group mt-5">
            <%= f.input :car_available, class: "form-control" %>
          </div>
        </div>
        <div class="col-md-4 select">
          <div class="form-group mt-5">
            <%= f.label :category %>
            <%= f.select :category, [["Cabrio", "Cabrio"], ["SUV", "SUV"], ["Minivan", "Minivan"], ["Sedan", "Sedan"], ["Coupe", "Coupe"], ["StationWagon", "StationWagon"], ["Hatchback", "hatchback"], ["Sportscar", "Sportscar"]], class: "form-control" %>
          </div>
        </div>
        <div class="col-md-4 select">
          <div class="form-group mt-5">
            <%= f.label :space_available %>
            <%= f.select :space_available, [[1, 1],[2, 2], [3, 3], [4, 4],[5, 5], [6, 6], [7, 7], [8, 8], [9, 9]], class: "form-control" %>
          </div>
        </div>
        <div class="col-md-4 select">
          <div class="form-group">
            <%= f.label :photos %>
            <%= f.input :photos, as: :file, class: "form-control", input_html: {multiple: true} %>
            <div id="image-preview"></div>
          </div>
        </div>
        <div class="form-group"><%= f.submit class: "btn btn-primary" %></div>
        </div>
      <% end %>
    </div>
  </div>
</div>


<!-- Add this to your form -->
<script>
  const input = document.querySelector('input[type="file"]');
  const preview = document.querySelector('#image-preview');

  input.addEventListener('change', () => {
    preview.innerHTML = ''; // Clear previous previews

    const files = Array.from(input.files);
    files.forEach((file) => {
      const reader = new FileReader();
      reader.onload = () => {
        const img = document.createElement('img');
        img.src = reader.result;
        img.classList.add('preview-image');
        preview.appendChild(img);
      };
      reader.readAsDataURL(file);
    });
  });
</script>

<style>
  .preview-image {
    max-width: 200px;
    max-height: 200px;
    margin-right: 10px;
  }
</style>

app/views/cars/index.html.erb
<div class="container container-car-list">
  <br>
  <div class="container card text-center p-1 w-50 rounded">
    <h3 class="mt-3"><strong>Wonderfull Cars</strong></h3>
  </div>
  <br>
  <div class="row" id="ads">
    <!-- Category Card -->

    <% @cars.each do |car| %>
      <div class="container col-md-3 col-4" data-controller="booked-date" data-booked-date-unavailable-value="<%= car.unavailable? %>" data-booked-date-ends-at-value="<%= car.current_booking_ends_at if car.current_booking %>" style="margin-top:50px;">
          <div>
            <div class="card-sl" data-booked-date-target="notAvailable">
              <div class="card-image">
                  <img
                      src="https://images.pexels.com/photos/1149831/pexels-photo-1149831.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940" />
              </div>

              <a class="card-action" data-action="click->booked-date#finishDate" href="#"><i class="fa-solid fa-car"></i></a>
              <div class="card-heading">
                  <%="#{car.brand} #{car.model}" %>
              </div>
              <div class="card-text">

              </div>
              <div class="card-text">
                  <h4><%= "#{car.price_per_day.to_i} € per day" %></h4>
              </div>
              <%= link_to car_path(car), class:"card-button" do %>
                <button class="card-button"> Rent Now</button>
              <% end %>
            </div>
          </div>
        </div>
    <% end %>
  </div>
</div>

app/views/cars/new.html.erb
<div class="container mt-5">
  <div class="newsletter-subscribe">
    <div class="container">
      <div class="intro">
        <h2 class="text-center">List your car</h2>
        <p class="text-center">Details for the car you want to add</p>
      </div>
    <div class="container p-2 mt-5">
      <%= simple_form_for (@car), html: { class: "form"} do |f| %>
        <div class="row">
          <div class="col-md-4 select">
            <div class="form-group">
              <%= f.input :brand, class: "form-control" %>
            </div>
          </div>
          <div class="col-md-4 select">
            <div class="form-group">
              <%= f.input :model, class: "form-control bg-primary" %>
            </div>
          </div>
          <div class="col-md-4 select">
            <div class="form-group">
              <%= f.input :price_per_day, class: "form-control" %>
            </div>
          </div>
          <div class="col-md-4 select">
            <div class="form-group">
              <%= f.input :location, class: "form-control" %>
            </div>
          </div>
          <div class="col-md-4 select">
            <div class="form-group">
              <%= f.input :year, class: "form-control" %>
            </div>
          </div>
          <div class="col-md-4 select">
            <div class="form-group mt-5">
            <%= f.label :fuel_type %>
              <%= f.select :fuel_type, [["Gasoline", "Gasolin"], ["Diesel", "Diesel"], ["GPL", "GPL"], ["Electric", "Electric"]], class:"form-select", aria_label:"Default select example" %>
            </div>
          </div>
          <div class="col-md-4 select">
            <div class="form-group mt-5">
              <%= f.input :car_available, class: "form-control" %>
            </div>
          </div>
          <div class="col-md-4 select">
            <div class="form-group mt-5">
            <%= f.label :category %>
              <%= f.select :category, [["Cabrio", "Cabrio"], ["SUV", "SUV"], ["Minivan", "Minivan"], ["Sedan", "Sedan"], ["Coupe", "Coupe"], ["StationWagon", "StationWagon"], ["Hatchback", "hatchback"], ["Sportscar", "Sportscar"]], class: "form-control" %>
            </div>
          </div>
          <div class="col-md-4 select">
            <div class="form-group mt-5">
              <%= f.label :space_available %>
              <%= f.select :space_available, [[1, 1],[2, 2], [3, 3], [4, 4],[5, 5], [6, 6], [7, 7], [8, 8], [9, 9]], class: "form-control" %>
            </div>
          </div>
          <div class="form-group">
              <%= f.label :photos %>
              <%= f.input :photos, as: :file, class: "form-control", input_html: {multiple: true} %>
              <div id="image-preview"></div>
            </div>
          <div class="form-group"><%= f.submit class: "btn btn-primary" %></div>
        </div>
      <% end %>
  </div>
</div>

<script>
  const input = document.querySelector('input[type="file"]');
  const preview = document.querySelector('#image-preview');

  input.addEventListener('change', () => {
    preview.innerHTML = ''; // Clear previous previews

    const files = Array.from(input.files);
    files.forEach((file) => {
      const reader = new FileReader();
      reader.onload = () => {
        const img = document.createElement('img');
        img.src = reader.result;
        img.classList.add('preview-image');
        preview.appendChild(img);
      };
      reader.readAsDataURL(file);
    });
  });
</script>

<style>
  .preview-image {
    max-width: 200px;
    max-height: 200px;
    margin-right: 10px;
  }
</style>

app/views/cars/show.html.erb
<div class="container my-5">
  <div class="card mb-3">
    <div class="row g-0">
      <div class="col-md-6">
        <div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel">
          <div class="carousel-indicators">
            <% @car.photos.each_with_index do |photo, index| %>
              <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="<%= index %>" class="<%= index == 0 ? "active" : "" %>" aria-current="<%= index == 0 ? "true" : "false" %>" aria-label="Slide <%= index + 1 %>"></button>
            <% end %>
          </div>
          <div class="carousel-inner">
            <% @car.photos.each_with_index do |photo, index| %>
              <div class="carousel-item <%= index == 0 ? "active" : "" %>">
                <%= cl_image_tag photo.key, height: 400, width: 600, crop: :fill, class: "rounded" %>
              </div>
            <% end %>
          </div>
          <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
          </button>
          <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
          </button>
        </div>
      </div>
      <div class="col-md-6">
        <div class="card-body">
          <%= button_to car_path(@car), method: :delete, form: { data: { turbo_confirm: "Are you sure?" } }, style:"border:none", class:"my_class" do %>
            <i class="fa-solid fa-trash-can"></i>
          <% end %>
          <h5 class="card-title fw-bold text-primary mb-4"><%= @car.brand %> <%= @car.model %></h5>
          <ul class="list-unstyled mb-3">
            <li><strong>Fuel Type:</strong> <span><%= @car.fuel_type %></span></li>
            <li><strong>Category:</strong> <span><%= @car.category %></span></li>
            <li><strong>Location:</strong> <span><%= @car.location %></span></li>
            <li><strong>Year:</strong> <span><%= @car.year %></span></li>
            <li><strong>Space Available:</strong> <span><%= @car.space_available %></span></li>
            <li><strong>Price Per Day:</strong> <span><%= @car.price_per_day %></span></li>
            <li><strong>Car Available:</strong> <span><%= @car.car_available ? 'Yes' : 'No' %></span></li>
          </ul>
        <div class="d-grid gap-2">
          <%= link_to "Book Now", new_car_booking_path(@car), class: "button-85", role: "button" %>
          <%= link_to "Edit Car", edit_car_path(@car), class: "button-85", role: "button" %>
        </div>
      </div>
    </div>
  </dib>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Carbnb</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= yield %>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner">
  <h1 data-controller="typed-js"></h1>

</div>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
  </div>
  <div class="footer-copyright">
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid d-flex justify-content-between">
    <div>
      <%= link_to root_path, class: "" do %>
        <%= image_tag "car-logo.svg", width: 100 %>
      <% end %>
    </div>

    <h2 class="m-0" id="title">CAR BNB</h2>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <% if request.fullpath == "/" %>
            <li class="nav-item dropdown">
              <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
              <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                <%= link_to "List Cars", cars_path, class: "dropdown-item" %>
                <%= link_to "Add a Car", new_car_path, class: "dropdown-item" %>
                <%= link_to "Log out", destroy_user_session_path, class: "dropdown-item", data: {turbo_method: :delete} %>
              </div>
            </li>
          <% else %>
            <li class="nav-item active">
              <%= link_to "", root_path, class: "nav-link" %>
            <li class="nav-item dropdown">
              <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
              <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                <%= link_to "List Cars", cars_path, class: "dropdown-item" %>
                <%= link_to "Add a Car", new_car_path, class: "dropdown-item" %>
                <%= link_to "Log out", destroy_user_session_path, class: "dropdown-item", data: {turbo_method: :delete} %>
              </div>
            </li>
          <% end %>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
           <li class="nav-item">
            <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Gloock&display=swap" rel="stylesheet">